### PR TITLE
Fixed LogUtil NullPointerException. Closes #8

### LINKED ISSUE #8: Fix NPE in LogUtil
Incorrect configuring leads to NullPointerException in LogUtil.

### PR DESCRIPTION
**Pull request by serlodkin**
Fixed LogUtil NullPointerException. Closes #8

### CODE REVIEW

File: src/main/java/org/search/system/utils/LogUtil.java [hunk 1]
```diff
@@ -24,6 +24,7 @@ of this software and associated documentation files (the "Software"), to deal
 
 package org.search.system.utils;
 
+import com.google.common.base.Objects;
```
Comment (matkovd) [inline src/main/java/org/search/system/utils/LogUtil.java]: This makes compliation fail, you try to import both `com.google.common.base.Objects` and `java.util.Objects`, just remove this line and everything would be ok

**Comment by matkovd** [comment]
Thanks!
